export const ADD_DATA_CHART_PORTION = "ADD_DATA_CHART_PORTION";
export const OPEN_MODAL_SUCCESS_PORTION = "OPEN_MODAL_SUCCESS_PORTION";
export const CLOSE_MODAL_SUCCESS_PORTION = "OPEN_MODAL_SUCCESS_PORTION";
export const OPEN_MODAL_DIAGRAM_PORTION = "OPEN_MODAL_DIAGRAM_PORTION";